import type { UiLocale } from './locale';
export interface UiMessages {
  close: string; loading: string; emptyTitle: string; emptyDescription: string; errorTitle: string; errorDescription: string; retry: string; permissionDeniedTitle: string; permissionDeniedDescription: string; confirm: string; cancel: string; noData: string; empty: string; error: string; permissionDenied: string; search: string; clear: string; select: string; delete: string; deleteConfirmation: string; download: string; upload: string; print: string; previous: string; next: string; create: string; edit: string; save: string; actions: string; navigationMenu: string; compactSidebar: string; themeCustomizer: string; notifications: string; profileSettings: string;
  filters: string; resetFilters: string; applyFilters: string; operationConfirmation: string; markAllRead: string; noNotifications: string; more: string; copy: string; copied: string; group: string; disabled: string; items: string; date: string; chooseDate: string; yes: string; no: string;
  tableSettings: string; tableView: string; tableViewDescription: string; sort: string; sortBy: string; ascending: string; descending: string; rowsPerPage: string; requestPageSize: string; visibleColumns: string; records: string; noRecords: string; refresh: string; globalSearch: string; bulkDelete: string; clearSelection: string; expandAll: string; collapseAll: string; view: string; remove: string; closeDialog: string; copyText: string; copyRecord: string; createTitle: string; editTitle: string; deleteItemTitle: string; deleteItemDescription: string; deleteSelectedDescription: string; irreversibleAction: string; exportReport: string; printDate: string; total: string; serverError: string; networkError: string; unexpectedError: string; downloadStarted: string; fileUnavailable: string;
}
export type UiMessageKey = keyof UiMessages;
export type UiMessageOverrides = Partial<UiMessages>;
export type UiMessageCatalog = Partial<Record<UiLocale, UiMessageOverrides>>;
export type UiMessageParams = Record<string, string | number | boolean>;
