import { IconAlertCircle, IconBell, IconChevronDown, IconMenu2, IconPalette, IconRefresh, IconSettings } from '@tabler/icons-vue';
import { ModernTheme } from '../theme/lightThemes/ModernTheme';
import { DarkModernTheme } from '../theme/darkThemes/DarkModernTheme';
import type { UiMessages, UiSemanticIcons, UiThemeRegistry } from './types';

export const defaultMessages: Record<'fa-IR' | 'en-US', UiMessages> = {
  'en-US': { loading: 'Please wait', emptyTitle: 'No results', emptyDescription: 'There is nothing to display.', errorTitle: 'Something went wrong', errorDescription: 'Please try again.', retry: 'Try again', permissionDeniedTitle: 'Access denied', permissionDeniedDescription: 'You do not have permission to view this content.', confirm: 'Confirm', cancel: 'Cancel', close: 'Close', noData: 'No data', empty: 'Empty', error: 'Error', permissionDenied: 'Permission denied', search: 'Search', clear: 'Clear', select: 'Select', delete: 'Delete', deleteConfirmation: 'Delete {count} item(s)?', download: 'Download', upload: 'Upload', print: 'Print', previous: 'Previous', next: 'Next', create: 'Create', edit: 'Edit', save: 'Save', actions: 'Actions', navigationMenu: 'Open navigation menu', compactSidebar: 'Toggle compact sidebar', themeCustomizer: 'Open theme customizer', notifications: 'Open notifications', profileSettings: 'Open profile settings' },
  'fa-IR': { loading: 'لطفا منتظر بمانید', emptyTitle: 'نتیجه‌ای یافت نشد', emptyDescription: 'موردی برای نمایش وجود ندارد.', errorTitle: 'خطایی رخ داد', errorDescription: 'لطفا دوباره تلاش کنید.', retry: 'تلاش مجدد', permissionDeniedTitle: 'دسترسی غیرمجاز', permissionDeniedDescription: 'شما اجازه مشاهده این محتوا را ندارید.', confirm: 'تایید', cancel: 'انصراف', close: 'بستن', noData: 'داده‌ای وجود ندارد', empty: 'خالی', error: 'خطا', permissionDenied: 'دسترسی غیرمجاز', search: 'جستجو', clear: 'پاک کردن', select: 'انتخاب', delete: 'حذف', deleteConfirmation: 'حذف {count} مورد؟', download: 'دانلود', upload: 'بارگذاری', print: 'چاپ', previous: 'قبلی', next: 'بعدی', create: 'ایجاد', edit: 'ویرایش', save: 'ذخیره', actions: 'عملیات', navigationMenu: 'باز کردن منوی ناوبری', compactSidebar: 'تغییر حالت فشرده نوار کناری', themeCustomizer: 'باز کردن تنظیمات پوسته', notifications: 'باز کردن اعلان‌ها', profileSettings: 'باز کردن تنظیمات پروفایل' }
};

export const defaultIcons: UiSemanticIcons = { close: 'mdi-close', confirm: 'mdi-check', cancel: 'mdi-close', loading: IconRefresh, empty: IconAlertCircle, error: IconAlertCircle, permissionDenied: IconAlertCircle, retry: IconRefresh, menu: IconMenu2, theme: IconPalette, notifications: IconBell, profile: IconSettings, chevronDown: IconChevronDown, search: 'mdi-magnify', clear: 'mdi-close-circle-outline', delete: 'mdi-delete-outline', edit: 'mdi-pencil-outline', create: 'mdi-plus', download: 'mdi-download', upload: 'mdi-upload', print: 'mdi-printer', previous: 'mdi-chevron-left', next: 'mdi-chevron-right', warning: 'mdi-alert-outline', success: 'mdi-check-circle-outline', expand: 'mdi-chevron-down', collapse: 'mdi-chevron-up' };
export const defaultThemes = { modern: ModernTheme, 'modern-dark': DarkModernTheme } satisfies UiThemeRegistry;
