import { IconAlertCircle, IconBell, IconChevronDown, IconMenu2, IconPalette, IconRefresh, IconSettings } from '@tabler/icons-vue';
import { ModernTheme } from '../theme/lightThemes/ModernTheme';
import { DarkModernTheme } from '../theme/darkThemes/DarkModernTheme';
import type { UiMessages, UiSemanticIcons, UiThemeRegistry } from './types';

export const defaultMessages: Record<'fa-IR' | 'en-US', UiMessages> = {
  'en-US': { loading: 'Please wait', emptyTitle: 'No results', emptyDescription: 'There is nothing to display.', errorTitle: 'Something went wrong', errorDescription: 'Please try again.', retry: 'Try again', permissionDeniedTitle: 'Access denied', permissionDeniedDescription: 'You do not have permission to view this content.', confirm: 'Confirm', cancel: 'Cancel', close: 'Close', noData: 'No data', empty: 'Empty', error: 'Error', permissionDenied: 'Permission denied', search: 'Search', clear: 'Clear', select: 'Select', delete: 'Delete', deleteConfirmation: 'Delete {count} item(s)?', download: 'Download', upload: 'Upload', print: 'Print', previous: 'Previous', next: 'Next', create: 'Create', edit: 'Edit', save: 'Save', actions: 'Actions', navigationMenu: 'Open navigation menu', compactSidebar: 'Toggle compact sidebar', themeCustomizer: 'Open theme customizer', notifications: 'Open notifications', profileSettings: 'Open profile settings', filters: 'Filters', resetFilters: 'Clear filters', applyFilters: 'Apply filters', operationConfirmation: 'Confirm operation', markAllRead: 'Mark all as read', noNotifications: 'No notifications', more: 'More', copy: 'Copy', copied: 'Copied', group: 'Group', disabled: 'Disabled', items: 'items', date: 'Date', chooseDate: 'Choose date', yes: 'Yes', no: 'No', tableSettings: 'Table settings', tableView: 'Table view', tableViewDescription: 'Sorting and visible columns', sort: 'Sorting', sortBy: 'Sort by', ascending: 'Ascending', descending: 'Descending', rowsPerPage: 'Rows per page', requestPageSize: 'Records per request', visibleColumns: 'Visible columns', records: 'records', noRecords: 'No records found', refresh: 'Refresh', globalSearch: 'Global search', bulkDelete: 'Delete selected', clearSelection: 'Clear selection', expandAll: 'Expand all', collapseAll: 'Collapse all', view: 'View', remove: 'Delete', closeDialog: 'Close', copyText: 'Copy text', copyRecord: 'Copy full record', createTitle: 'Create', editTitle: 'Edit', deleteItemTitle: 'Delete item', deleteItemDescription: 'Do you want to delete this record?', deleteSelectedDescription: 'Do you want to delete {count} selected item(s)?', irreversibleAction: 'This action cannot be undone.', exportReport: 'Full report', printDate: 'Print date', total: 'Total', serverError: 'Server error', networkError: 'Network error. Please try again.', unexpectedError: 'An unexpected error occurred.', downloadStarted: 'Download started', fileUnavailable: 'File is unavailable' },
  'fa-IR': { loading: 'لطفا منتظر بمانید', emptyTitle: 'نتیجه‌ای یافت نشد', emptyDescription: 'موردی برای نمایش وجود ندارد.', errorTitle: 'خطایی رخ داد', errorDescription: 'لطفا دوباره تلاش کنید.', retry: 'تلاش مجدد', permissionDeniedTitle: 'دسترسی غیرمجاز', permissionDeniedDescription: 'شما اجازه مشاهده این محتوا را ندارید.', confirm: 'تایید', cancel: 'انصراف', close: 'بستن', noData: 'داده‌ای وجود ندارد', empty: 'خالی', error: 'خطا', permissionDenied: 'دسترسی غیرمجاز', search: 'جستجو', clear: 'پاک کردن', select: 'انتخاب', delete: 'حذف', deleteConfirmation: 'حذف {count} مورد؟', download: 'دانلود', upload: 'بارگذاری', print: 'چاپ', previous: 'قبلی', next: 'بعدی', create: 'ایجاد', edit: 'ویرایش', save: 'ذخیره', actions: 'عملیات', navigationMenu: 'باز کردن منوی ناوبری', compactSidebar: 'تغییر حالت فشرده نوار کناری', themeCustomizer: 'باز کردن تنظیمات پوسته', notifications: 'باز کردن اعلان‌ها', profileSettings: 'باز کردن تنظیمات پروفایل', filters: 'فیلترها', resetFilters: 'پاک‌کردن فیلترها', applyFilters: 'اعمال فیلتر', operationConfirmation: 'تأیید عملیات', markAllRead: 'خوانده شد', noNotifications: 'اعلانی وجود ندارد', more: 'بیشتر', copy: 'کپی', copied: 'کپی شد', group: 'گروه', disabled: 'غیرفعال', items: 'آیتم', date: 'تاریخ', chooseDate: 'انتخاب کنید', yes: 'بله', no: 'خیر', tableSettings: 'تنظیمات جدول', tableView: 'نمای جدول', tableViewDescription: 'مرتب‌سازی و ستون‌های قابل نمایش', sort: 'مرتب‌سازی', sortBy: 'مرتب‌سازی بر اساس', ascending: 'صعودی', descending: 'نزولی', rowsPerPage: 'تعداد ردیف هر صفحه', requestPageSize: 'تعداد رکورد در درخواست', visibleColumns: 'نمایش ستون‌ها', records: 'رکورد', noRecords: 'رکوردی یافت نشد', refresh: 'بروزرسانی', globalSearch: 'جستجو کلی', bulkDelete: 'حذف گروهی', clearSelection: 'پاک کردن انتخاب', expandAll: 'گسترش همه', collapseAll: 'جمع کردن همه', view: 'نمایش', remove: 'حذف', closeDialog: 'بستن', copyText: 'کپی متن', copyRecord: 'کپی رکورد کامل', createTitle: 'ایجاد', editTitle: 'ویرایش', deleteItemTitle: 'حذف آیتم', deleteItemDescription: 'آیا مایل به حذف این رکورد هستید؟', deleteSelectedDescription: 'آیا مایل به حذف {count} آیتم انتخاب شده هستید؟', irreversibleAction: 'این عمل قابل بازگشت نیست!', exportReport: 'گزارش کلی', printDate: 'تاریخ چاپ', total: 'جمع کل', serverError: 'خطای سرور', networkError: 'خطای شبکه. لطفا دوباره تلاش کنید.', unexpectedError: 'یک خطای غیرمنتظره رخ داد.', downloadStarted: 'دانلود شروع شد', fileUnavailable: 'فایل در دسترس نیست' }
};

export const defaultIcons: UiSemanticIcons = { close: 'mdi-close', confirm: 'mdi-check', cancel: 'mdi-close', loading: IconRefresh, empty: IconAlertCircle, error: IconAlertCircle, permissionDenied: IconAlertCircle, retry: IconRefresh, menu: IconMenu2, theme: IconPalette, notifications: IconBell, profile: IconSettings, chevronDown: IconChevronDown, search: 'mdi-magnify', clear: 'mdi-close-circle-outline', delete: 'mdi-delete-outline', edit: 'mdi-pencil-outline', create: 'mdi-plus', download: 'mdi-download', upload: 'mdi-upload', print: 'mdi-printer', previous: 'mdi-chevron-left', next: 'mdi-chevron-right', warning: 'mdi-alert-outline', success: 'mdi-check-circle-outline', expand: 'mdi-chevron-down', collapse: 'mdi-chevron-up' };
export const defaultThemes = { modern: ModernTheme, 'modern-dark': DarkModernTheme } satisfies UiThemeRegistry;
